### ISSUE TITLE
Can't find this package on PackageControl

### ISSUE THREAD

**Issue by jostyee** [alecthomas/SublimeLinter-contrib-golang-cilint#1]
https://packagecontrol.io/search/golangci

> No packages matched your search terms

**Comment by mwei0210** [comment]
bump

**Comment by asfaltboy** [comment]
@alecthomas someone already created a PR but they need your help to conclude; see SublimeLinter/package_control_channel#83

**Comment by alecthomas** [comment]
Yep he's talked to me and is sending a PR through at some point.

**Comment by alecthomas** [comment]
https://github.com/cixtor/SublimeLinter-golangcilint
