### ISSUE TITLE
Not working on errors without column?

### ISSUE THREAD

**Issue by otto-md** [alecthomas/SublimeLinter-contrib-golang-cilint#2]
```
store_test.go:21:7: undeclared name: pq (typecheck)
store_test.go:8: File is not goimports-ed (goimports)
```
The typecheck error is picked up by SublimeLinter, the goimports one is not. I get this in the console:
`SublimeLinter: #6 linter.py:995: golangcilint: No match for line: 'store_test.go:8: File is not goimports-ed (goimports)'`

Maybe the `regex = r'(?:[^:]+):(?P<line>\d+):(?P<col>\d+)?:\s*(?P<message>.*)'` is wrong?

**Comment by alecthomas** [comment]
https://github.com/cixtor/SublimeLinter-golangcilint
